### ISSUE TITLE
Translations do not work in items and scoreboard

### ISSUE THREAD

**Issue by maltl00r** [tritonmc/Triton#139]
**Describe the bug**
- Translations in items are not visible unless you open a menu external to the player (Im use ItemJoin for the items)
- Translations in the scoreboard do not work (Im use the TAB plugin).
- Maybe the PlaceholderAPI variables are not supported yet :(

**To Reproduce**
None (?). When i open a menu the translations are visible
**Expected behavior**
Translations to appear as they do in text & holograms.

**Screenshots (optional)**
Video link: https://youtu.be/e-vRkaTQB9c

**Server information (please complete the following information):**
 - Server Minecraft Version: [PaperSpigot 1.8.8]
 - Client Minecraft Version : [1.8.9 (Using ViaVersion)]
 - BungeeCord (specify if it's a fork) [yes, i use FlameCord]
 - Triton Version: [3.2.2]

**Additional context**
- There are no console errors.
- The video translations were on the spigot server and not on the bungeecord server.
- My server is a network.
- I have 2 languages (English and Spanish)
- The menu presented is a custom one made with deluxemenus.
- Now I am using local data to test but later I plan to connect it using mysql.
- Im spanish and my server has spanish translations (sorry about this)
**Plugins Versions**
- DeluxesMenus [1.10.5]
- ItemJoin [5.0.6-RELEASE-b395]
- TAB Premium [2.7.5]

**Comment by diogotcorreia** [comment]
Hi! None of what you said is a bug, they're all intended features.

- Translations in items outside of GUIs are disabled by default due to compatibility issues with the creative gamemode. However, enabling them is as easy as setting `allow-in-inventory` to `true` on [config.yml](https://github.com/tritonmc/Triton/blob/master/config.yml#L180).
- Scoreboards can't be translated with Triton's Placeholders due to a number of technical challenges, as stated in the Limitations section of the resource page on Spigot, but you can [use PlaceholderAPI as an alternative](https://triton.rexcantor64.com/concepts/placeholderapi.html) if your scoreboard plugin supports it.
- Finally, it is not possible to use variables with PlaceholderAPI because that's a limitation of PlaceholderAPI, not Triton. PAPI was never intended to translate stuff, so it's not designed to do so.

Also, thank you a lot for including so much information (and a video!) in your issue, it makes replying a lot easier 😄
