### ISSUE TITLE
translated message not appear with player kick on BungeeCord LoginEvent

### ISSUE THREAD

**Issue by DAYELA** [tritonmc/Triton#191]
in a custom plugin (Bungeecord) I kick players who try to connect to the server without permission with a merssage translated by triton inside a Bungeecord LoginEvent. The message sent is "[lang]Common.error.server_join_permission[/lang]" but the message translated by triton does not appear sometimes on the screen and there is no error in the log.

Here is the code to reproduce:

` 
public void onLogin(LoginEvent) {
                event.setCancelled(true);
                event.setCancelReason(new TextComponent("[lang]Common.error.server_join_permission[/lang]"));
    }`

The translated text by triton should appear on the screen

 - Server Minecraft Version: 1.8.8
 - Client Minecraft Version (if using ViaVersion or something similar): 1.8.8
 - BungeeCord (specify if it's a fork): Yes adn this is a fork: FlameCord
 - Triton Version: v3.7.1

**Comment by diogotcorreia** [comment]
If the message isn't show, what message shows up instead?
I've tried reproducing the error, but it always works for me:
![image](https://user-images.githubusercontent.com/7467891/179420912-12850a2f-0ebe-4d53-8bb7-c1f2ff01ef25.png)

The only other message I can get is a "Failed to login: null", which I assume is some sort of rate limiting, since it only happens if I try to spam join.
![image](https://user-images.githubusercontent.com/7467891/179420975-03372907-b3f2-49d5-9b64-386a96d75f66.png)


I've used the code you gave me in a standalone plugin. What event priority do you have? I've tried with the default one.

I've also tried with local storage and mysql, neither of them show the issue.
I'm using the latest FlameCord from their git repository (1.0.4).

Please comment below or contact me on Discord if the issue is still not fixed
