### ISSUE TITLE
TritonAPI always null on FlameCord

### ISSUE THREAD

**Issue by Whitescan** [tritonmc/Triton#256]
### Describe the bug

Using [FlameCord](https://github.com/2lstudios-mc/FlameCord) the TritonAPI#getInstance() method seems to always return null.

### How can the bug be reproduced?

1. Setup Triton on a FlameCord / Waterfall Server
2. Make a Plugin using the TritonAPI

pom.xml:
```
<repository>
  <id>jitpack.io</id>
  <url>https://jitpack.io</url>
</repository>
				
<!-- Triton API -->
<dependency>
  <groupId>com.github.Rexcantor</groupId>
  <artifactId>Triton</artifactId>
  <version>3.8.2</version>
  <scope>provided</scope>
</dependency>
```

Retrieve the TritonAPI using:
```
private static final Triton tritonAPI = TritonAPI.getInstance();
```

Trying to translate any message results in NullPointerException

### Expected behaviour

The API should be retrieved and fully operational. 
Or at least have a way to run code once the API is operational.

### Which Spigot fork are you using?

Other (specify below)

### What's your server version?

git-Purpur-1778 (MC: 1.19.2)

### Which proxy are you using?

FlameCord

### What's your proxy version?

FlameCord version 1.1.3

### What's the MC version of your client?

1.19.2

### What's the Triton version you're using?

3.8.2

**Comment by diogotcorreia** [comment]
Hi!
This happens because you're trying to get the instance of the plugin before it has been loaded.

The code you provided,
```java
private static final Triton tritonAPI = TritonAPI.getInstance();
```

gets the instance of Triton as soon as the bytecode for that class is loaded into the Java Virtual Machine (JVM).

You may try loading it only after Triton has loaded (i.e. on your `onEnable()` method if your plugin `depends` on Triton on `plugin.yml`/`bungee.yml`). That should fix the issue!
