### ISSUE TITLE
Would like to know which plugins openly state that they support Triton and are language ready out of the box

### ISSUE THREAD

**Issue by 8MiYile** [tritonmc/Triton#280]
Want to know what functional plugins work in conjunction with the Triton plugin
means that some functional plugins have built-in Triton translation bars to facilitate the display of languages through Triton

In short, I need a list of plugins that support the Triton language system

**Comment by diogotcorreia** [comment]
Hi!
There isn't a list because plugins do not hook directly into Triton, Triton intercepts their packets and replaces placeholders with the respective text.

The requirement for a plugin to work correctly is that you can change its messages. Scoreboard messages can only be translated through PlaceholderAPI and not Triton placeholders.

As some people has said on Discord, there are a few plugins that might not work perfectly, but it's better to has for those individually. Ideally, Triton would work correctly with all of them and that's the goal of this project.
