### ISSUE TITLE
Executable commands from chat

### ISSUE THREAD

**Issue by tyuop077** [tritonmc/Triton#90]
(executes command as soon as it gets a string [exec]my.example.key[/exec] ("my.example.key" - any key)
![image](https://user-images.githubusercontent.com/30123136/76305190-bdcb6100-62d5-11ea-8906-b77aa9af90bd.png)
Works as disabled line, but also execute command. Works only from chat message.

Example: Separate French players and English-language players to another bedwars games.
![image](https://user-images.githubusercontent.com/30123136/76305998-32eb6600-62d7-11ea-9abd-edc9dc47333f.png)
![image](https://user-images.githubusercontent.com/30123136/76306656-5e228500-62d8-11ea-8fe0-21219698739e.png)
It will join player to English arena or French arena by the language.
Syntax will be exact same as "first join / change language" command.

**Comment by diogotcorreia** [comment]
Thanks a lot for your feature request. However, it seems to be a very specific request. I'm a bit sceptical about triggering commands on chat messages because it could be abused.

I was thinking it could be made another way. Here are my thoughts on it:
- Instead of triggering with a chat message, create a command (e.g. `/triton exec`) that could trigger this.
- Have separate permissions for triggering player-run and server-run commands.
	- _(OR)_ instead have permissions per command (?)


What is your opinion on this?

**Comment by tyuop077** [comment]
Resolved
